###
GET http://localhost:4004/odata/v4/api-service-consumption/getTemplateFile(eventId='Doc3032082443')

###
POST http://localhost:4004/odata/v4/api-service-consumption/downloadTemplateFile
Content-Type: application/json

{
  "downloadId": "f314081b-e7f2-4bcb-beba-bdaff210462a"
}

###
POST http://localhost:4004/odata/v4/api-service-consumption/sendToDocusign
Content-Type: application/json

{
  "signerEmail": "gpraveen9870@gmail.com",
  "signerName": "Praveen Kumar G"
}

###
POST http://localhost:4004/odata/v4/api-service-consumption/downloadSignedPdf
Content-Type: application/json

{
  "envelopeId" : "48e42b32-2aa8-80a0-812c-72aa5c5b18e5"
}

###
POST http://localhost:4004/odata/v4/api-service-consumption/sendToDocusign
Content-Type: application/json

{
  "signerEmail": "sreyabommidala@gmail.com",
  "signerName": "Sreya Bommidala"
}
