###
GET http://localhost:45409/odata/v4/api-service-consumption/getTemplateFile(eventId='Doc3032082443')

###
POST http://localhost:4004/odata/v4/api-service-consumption/sendToDocusign
Content-Type: application/json

{
  "signerEmail": "gpraveen9870@gmail.com",
  "signerName": "Praveen Kumar G"
}